// Standard audit action types for consistent logging
export const AUDIT_ACTIONS = {
  // Authentication & Access
  ADMIN_ACCESS_GRANTED: 'admin_access_granted',
  ADMIN_ACCESS_DENIED: 'admin_access_denied',
  ADMIN_ACCESS_UNAUTHORIZED: 'admin_access_unauthorized',
  ADMIN_LOGOUT: 'admin_logout',
  SESSION_EXPIRED: 'admin_session_expired',
  SESSION_EXTENDED: 'admin_session_extended',
  
  // User Management
  USER_CREATED: 'user_created',
  USER_UPDATED: 'user_updated',
  USER_DELETED: 'user_deleted',
  USER_SUSPENDED: 'user_suspended',
  USER_ACTIVATED: 'user_activated',
  USER_PASSWORD_RESET: 'user_password_reset',
  USER_VIEWED: 'user_viewed',
  
  // Role Management
  ROLE_ASSIGNED: 'role_assigned',
  ROLE_REMOVED: 'role_removed',
  ROLE_UPDATED: 'role_updated',
  
  // Therapist Management
  THERAPIST_CREATED: 'therapist_created',
  THERAPIST_UPDATED: 'therapist_updated',
  THERAPIST_DELETED: 'therapist_deleted',
  THERAPIST_APPROVED: 'therapist_approved',
  THERAPIST_SUSPENDED: 'therapist_suspended',
  THERAPIST_ACTIVATED: 'therapist_activated',
  THERAPIST_VIEWED: 'therapist_viewed',
  
  // System Settings
  SETTINGS_UPDATED: 'settings_updated',
  SECURITY_SETTINGS_CHANGED: 'security_settings_changed',
  NOTIFICATION_SETTINGS_CHANGED: 'notification_settings_changed',
  PLATFORM_CONFIG_CHANGED: 'platform_config_changed',
  
  // System Actions
  DATABASE_BACKUP: 'database_backup_initiated',
  API_KEYS_ROTATED: 'api_keys_rotated',
  CACHE_CLEARED: 'cache_cleared',
  EMERGENCY_LOCKDOWN: 'emergency_lockdown_activated',
  
  // Portal Navigation
  PORTAL_ACCESSED: 'admin_portal_accessed',
  TAB_CHANGED: 'admin_tab_changed',
} as const;

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];

// Action categories for filtering
export const ACTION_CATEGORIES = {
  AUTHENTICATION: 'Authentication',
  USER_MANAGEMENT: 'User Management',
  ROLE_MANAGEMENT: 'Role Management',
  THERAPIST_MANAGEMENT: 'Therapist Management',
  SYSTEM_SETTINGS: 'System Settings',
  SYSTEM_ACTIONS: 'System Actions',
  NAVIGATION: 'Navigation',
} as const;

// Map actions to categories
export const actionToCategory: Record<string, string> = {
  [AUDIT_ACTIONS.ADMIN_ACCESS_GRANTED]: ACTION_CATEGORIES.AUTHENTICATION,
  [AUDIT_ACTIONS.ADMIN_ACCESS_DENIED]: ACTION_CATEGORIES.AUTHENTICATION,
  [AUDIT_ACTIONS.ADMIN_ACCESS_UNAUTHORIZED]: ACTION_CATEGORIES.AUTHENTICATION,
  [AUDIT_ACTIONS.ADMIN_LOGOUT]: ACTION_CATEGORIES.AUTHENTICATION,
  [AUDIT_ACTIONS.SESSION_EXPIRED]: ACTION_CATEGORIES.AUTHENTICATION,
  [AUDIT_ACTIONS.SESSION_EXTENDED]: ACTION_CATEGORIES.AUTHENTICATION,
  
  [AUDIT_ACTIONS.USER_CREATED]: ACTION_CATEGORIES.USER_MANAGEMENT,
  [AUDIT_ACTIONS.USER_UPDATED]: ACTION_CATEGORIES.USER_MANAGEMENT,
  [AUDIT_ACTIONS.USER_DELETED]: ACTION_CATEGORIES.USER_MANAGEMENT,
  [AUDIT_ACTIONS.USER_SUSPENDED]: ACTION_CATEGORIES.USER_MANAGEMENT,
  [AUDIT_ACTIONS.USER_ACTIVATED]: ACTION_CATEGORIES.USER_MANAGEMENT,
  [AUDIT_ACTIONS.USER_PASSWORD_RESET]: ACTION_CATEGORIES.USER_MANAGEMENT,
  [AUDIT_ACTIONS.USER_VIEWED]: ACTION_CATEGORIES.USER_MANAGEMENT,
  
  [AUDIT_ACTIONS.ROLE_ASSIGNED]: ACTION_CATEGORIES.ROLE_MANAGEMENT,
  [AUDIT_ACTIONS.ROLE_REMOVED]: ACTION_CATEGORIES.ROLE_MANAGEMENT,
  [AUDIT_ACTIONS.ROLE_UPDATED]: ACTION_CATEGORIES.ROLE_MANAGEMENT,
  
  [AUDIT_ACTIONS.THERAPIST_CREATED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  [AUDIT_ACTIONS.THERAPIST_UPDATED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  [AUDIT_ACTIONS.THERAPIST_DELETED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  [AUDIT_ACTIONS.THERAPIST_APPROVED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  [AUDIT_ACTIONS.THERAPIST_SUSPENDED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  [AUDIT_ACTIONS.THERAPIST_ACTIVATED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  [AUDIT_ACTIONS.THERAPIST_VIEWED]: ACTION_CATEGORIES.THERAPIST_MANAGEMENT,
  
  [AUDIT_ACTIONS.SETTINGS_UPDATED]: ACTION_CATEGORIES.SYSTEM_SETTINGS,
  [AUDIT_ACTIONS.SECURITY_SETTINGS_CHANGED]: ACTION_CATEGORIES.SYSTEM_SETTINGS,
  [AUDIT_ACTIONS.NOTIFICATION_SETTINGS_CHANGED]: ACTION_CATEGORIES.SYSTEM_SETTINGS,
  [AUDIT_ACTIONS.PLATFORM_CONFIG_CHANGED]: ACTION_CATEGORIES.SYSTEM_SETTINGS,
  
  [AUDIT_ACTIONS.DATABASE_BACKUP]: ACTION_CATEGORIES.SYSTEM_ACTIONS,
  [AUDIT_ACTIONS.API_KEYS_ROTATED]: ACTION_CATEGORIES.SYSTEM_ACTIONS,
  [AUDIT_ACTIONS.CACHE_CLEARED]: ACTION_CATEGORIES.SYSTEM_ACTIONS,
  [AUDIT_ACTIONS.EMERGENCY_LOCKDOWN]: ACTION_CATEGORIES.SYSTEM_ACTIONS,
  
  [AUDIT_ACTIONS.PORTAL_ACCESSED]: ACTION_CATEGORIES.NAVIGATION,
  [AUDIT_ACTIONS.TAB_CHANGED]: ACTION_CATEGORIES.NAVIGATION,
};
