import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { FileText, Download, Plus, Eye } from 'lucide-react';
import { jsPDF } from 'jspdf';
import type { AuditReport, ComplianceMetrics } from '@/hooks/useHIPAACompliance';
import type { UseMutationResult } from '@tanstack/react-query';

interface AuditReportingSectionProps {
  auditReports: AuditReport[];
  metrics: ComplianceMetrics;
  generateReport: UseMutationResult<any, Error, any, unknown>;
}

const AuditReportingSection: React.FC<AuditReportingSectionProps> = ({ auditReports, metrics, generateReport }) => {
  const [dialogOpen, setDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    type: 'HIPAA_Review',
    name: '',
    periodStart: '',
    periodEnd: '',
  });

  const handleGenerate = async () => {
    if (!formData.name || !formData.periodStart || !formData.periodEnd) return;
    
    await generateReport.mutateAsync({
      type: formData.type,
      name: formData.name,
      periodStart: formData.periodStart,
      periodEnd: formData.periodEnd,
    });

    setDialogOpen(false);
    setFormData({ type: 'HIPAA_Review', name: '', periodStart: '', periodEnd: '' });
  };

  const exportToPDF = (report: AuditReport) => {
    const doc = new jsPDF();
    const margin = 20;
    let y = margin;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(184, 115, 51); // Bronze color
    doc.text('ThriveMT', margin, y);
    y += 10;

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(report.report_name, margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Report Type: ${report.report_type.replace('_', ' ')}`, margin, y);
    y += 5;
    doc.text(`Period: ${report.period_start} to ${report.period_end}`, margin, y);
    y += 5;
    doc.text(`Generated: ${new Date(report.created_at).toLocaleDateString()}`, margin, y);
    y += 5;
    doc.text(`Generated By: ${report.generated_by_name || 'System'}`, margin, y);
    y += 15;

    // Summary Section
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Executive Summary', margin, y);
    y += 8;

    doc.setFontSize(10);
    const summary = report.summary as any;
    if (summary) {
      doc.text(`Total Audits Performed: ${summary.totalAudits || 0}`, margin, y);
      y += 5;
      doc.text(`Passed: ${summary.passed || 0}`, margin, y);
      y += 5;
      doc.text(`Failed: ${summary.failed || 0}`, margin, y);
      y += 5;
      doc.text(`Needs Remediation: ${summary.needsRemediation || 0}`, margin, y);
      y += 5;
      doc.text(`Open Remediations: ${summary.openRemediations || 0}`, margin, y);
      y += 5;
      doc.text(`Risk Assessments: ${summary.riskAssessments || 0}`, margin, y);
      y += 15;

      // Category Breakdown
      if (summary.byCategory) {
        doc.setFontSize(14);
        doc.text('Results by Category', margin, y);
        y += 8;

        doc.setFontSize(10);
        Object.entries(summary.byCategory).forEach(([category, data]: [string, any]) => {
          if (y > 270) {
            doc.addPage();
            y = margin;
          }
          const passRate = data.total > 0 ? Math.round((data.passed / data.total) * 100) : 100;
          doc.text(`${category}: ${data.passed}/${data.total} passed (${passRate}%)`, margin, y);
          y += 5;
        });
      }
    }

    // Compliance Statement
    y += 10;
    if (y > 250) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(14);
    doc.text('Compliance Statement', margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const statement = `This report documents the compliance audit activities conducted during the specified period. ` +
      `The organization maintains ongoing compliance monitoring in accordance with HIPAA Security Rule ` +
      `and SOC 2 Trust Services Criteria requirements. All findings are documented and remediation ` +
      `activities are tracked through completion.`;
    
    const lines = doc.splitTextToSize(statement, 170);
    doc.text(lines, margin, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('This document is confidential and intended for internal use only.', margin, 285);

    doc.save(`${report.report_name.replace(/\s+/g, '-')}-${report.period_end}.pdf`);
  };

  const getReportTypeBadge = (type: string) => {
    switch (type) {
      case 'SOC2_Type1': return 'bg-blue-500/20 text-blue-300 border-blue-500/50';
      case 'SOC2_Type2': return 'bg-purple-500/20 text-purple-300 border-purple-500/50';
      case 'HIPAA_Review': return 'bg-[#B87333]/20 text-[#E5C5A1] border-[#B87333]/50';
      case 'BAA_Review': return 'bg-green-500/20 text-green-300 border-green-500/50';
      default: return 'bg-gray-500/20 text-gray-300 border-gray-500/50';
    }
  };

  return (
    <div className="space-y-4">
      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card className="bg-gray-800/50 border border-gray-700">
          <CardContent className="pt-4">
            <div className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-[#B87333]" />
              <div>
                <div className="text-2xl font-bold text-white">{auditReports.length}</div>
                <p className="text-xs text-gray-400">Total Reports</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-[#B87333]/20 border border-[#B87333]/30">
          <CardContent className="pt-4">
            <div>
              <div className="text-2xl font-bold text-[#E5C5A1]">{metrics.hipaaCompliance}%</div>
              <p className="text-xs text-gray-400">Current HIPAA Score</p>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-blue-900/20 border border-blue-500/30">
          <CardContent className="pt-4">
            <div>
              <div className="text-2xl font-bold text-blue-400">{metrics.soc2Compliance}%</div>
              <p className="text-xs text-gray-400">Current SOC 2 Score</p>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-purple-900/20 border border-purple-500/30">
          <CardContent className="pt-4">
            <div>
              <div className="text-2xl font-bold text-purple-400">{metrics.soc2ReadinessScore}%</div>
              <p className="text-xs text-gray-400">Type 2 Readiness</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Reports Table */}
      <Card className="bg-gray-800/50 border border-gray-700">
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-lg text-white">Audit Reports</CardTitle>
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button className="bg-[#B87333] hover:bg-[#A06830] text-white">
                <Plus className="w-4 h-4 mr-2" />
                Generate Report
              </Button>
            </DialogTrigger>
            <DialogContent className="bg-gray-800 border-gray-700 text-white">
              <DialogHeader>
                <DialogTitle>Generate Audit Report</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <Label className="text-gray-300">Report Type</Label>
                  <Select value={formData.type} onValueChange={(val) => setFormData(prev => ({ ...prev, type: val }))}>
                    <SelectTrigger className="bg-gray-900/50 border-gray-600 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-gray-800 border-gray-700">
                      <SelectItem value="HIPAA_Review">HIPAA Compliance Review</SelectItem>
                      <SelectItem value="SOC2_Type1">SOC 2 Type 1 Simulation</SelectItem>
                      <SelectItem value="SOC2_Type2">SOC 2 Type 2 Simulation</SelectItem>
                      <SelectItem value="BAA_Review">BAA Compliance Review</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-gray-300">Report Name</Label>
                  <Input
                    value={formData.name}
                    onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                    placeholder="Q4 2025 HIPAA Review"
                    className="bg-gray-900/50 border-gray-600 text-white"
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-gray-300">Period Start</Label>
                    <Input
                      type="date"
                      value={formData.periodStart}
                      onChange={(e) => setFormData(prev => ({ ...prev, periodStart: e.target.value }))}
                      className="bg-gray-900/50 border-gray-600 text-white"
                    />
                  </div>
                  <div>
                    <Label className="text-gray-300">Period End</Label>
                    <Input
                      type="date"
                      value={formData.periodEnd}
                      onChange={(e) => setFormData(prev => ({ ...prev, periodEnd: e.target.value }))}
                      className="bg-gray-900/50 border-gray-600 text-white"
                    />
                  </div>
                </div>
                <Button 
                  onClick={handleGenerate} 
                  disabled={!formData.name || !formData.periodStart || !formData.periodEnd || generateReport.isPending}
                  className="w-full bg-[#B87333] hover:bg-[#A06830]"
                >
                  {generateReport.isPending ? 'Generating...' : 'Generate Report'}
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </CardHeader>
        <CardContent>
          {auditReports.length === 0 ? (
            <div className="text-center py-8 text-gray-400">
              No reports generated yet. Click "Generate Report" to create your first audit report.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="border-gray-700">
                    <TableHead className="text-gray-300">Report Name</TableHead>
                    <TableHead className="text-gray-300">Type</TableHead>
                    <TableHead className="text-gray-300">Period</TableHead>
                    <TableHead className="text-gray-300">Generated</TableHead>
                    <TableHead className="text-gray-300">Status</TableHead>
                    <TableHead className="text-gray-300 w-24">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {auditReports.map(report => (
                    <TableRow key={report.id} className="border-gray-700">
                      <TableCell className="text-white">{report.report_name}</TableCell>
                      <TableCell>
                        <Badge className={getReportTypeBadge(report.report_type)} variant="outline">
                          {report.report_type.replace('_', ' ')}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-gray-300 text-sm">
                        {report.period_start} — {report.period_end}
                      </TableCell>
                      <TableCell className="text-gray-300 text-sm">
                        {new Date(report.created_at).toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        <Badge className="bg-green-500/20 text-green-300 border-green-500/50" variant="outline">
                          {report.status}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Button 
                          variant="ghost" 
                          size="sm" 
                          onClick={() => exportToPDF(report)}
                          className="text-[#B87333] hover:text-[#E5C5A1]"
                        >
                          <Download className="w-4 h-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default AuditReportingSection;
