// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rreidjrluqkxwwhifwym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZWlkanJsdXFreHd3aGlmd3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTEyNzQsImV4cCI6MjA2NTU4NzI3NH0.h9GVqw0HyT9v1a6t4RTFNNU-_sJusKZpYn_VnJU-TUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});