// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ticsqdxjbttgrrhzfbgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpY3NxZHhqYnR0Z3JyaHpmYmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDMxNTQsImV4cCI6MjA2Nzc3OTE1NH0.2EK5gejCkx0qkCBECt3-vmaZ3Ar5UpTnIFUlpXYZQJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});